version: "3.1"

services:
  metabase:
    image: metabase/metabase:v0.46.6.4
    container_name: metabase
    hostname: metabase
    environment:
      - MB_DB_FILE=/metabase/metabase.db # check
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5  
    restart: always
    volumes:
      - ${PROJECT_DIR:-${PWD}}/metabase:/metabase-data